name: matrix
on: workflow_dispatch
jobs:
  matr:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest,ubuntu-latest]
    steps:
          - name: sample
            run: echo ${{matrix.os}}
  
