#Name of Workflow
name: ExportFromDevandPushToReop-V

#Trigger Flow Manually
on: 
  workflow_dispatch:
  

#Source and Destination Envirnoment Details
env:
  #envirnoments
  SOURCE_ENV_NAME: DEV
  SOURCE_ENV_URL: ${{ secrets.E2EDEV }}
  TARGET_ENV_NAME: QA
  TARGET_ENV_URL: ${{ secrets.E2EQA }}
  #service principal 
  APPID: ${{ secrets.APPID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  USERNAME: dharmicrm3@dharmicrm3.onmicrosoft.com
  password: Dharmi@220699
  #soluitons
  CUSTOMIZATION: poc1
  TABLES: poc2


jobs:
  Connection:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1
    steps:
      #checkout git repo
      - uses: actions/checkout@v2
        with:
          lfs: true
      #check the Service Principal Connection Validation
      - name: Connection-${{env.SOURCE_ENV_NAME}}
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          user-name: ${{env.USERNAME}}
          password-secret: ${{ env.password }}
      - name: Connection-${{env.TARGET_ENV_NAME}}
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
           user-name: ${{env.USERNAME}}
           password-secret: ${{ env.password }}
  #Export ManagesSolutions from Dev Environment
  ExportManaged-From-DEV:
    runs-on: windows-latest
    needs: [Connection]
    env:
      RUNNER_DEBUG: 1
    strategy:
      matrix: 
        solution: 
          - poc1
          - poc2
     
    steps:
      - name: Export solution ${{matrix.solution}}
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{env.SOURCE_ENV_URL}}
          app-id: ${{env.APPID}}
          client-secret: ${{env.CLIENT_SECRET}}
          tenant-id: ${{env.TENANT_ID}}
          solution-name: ${{matrix.solution}}
          managed: true
          solution-output-file: out/exportmanaged/${{matrix.solution}}.zip
      - name: Check Solution ${{matrix.solution}}
        uses: microsoft/powerplatform-actions/check-solution@v0
        with:
          environment-url: ${{env.SOURCE_ENV_URL}}
          app-id: ${{env.APPID}}
          client-secret: ${{env.CLIENT_SECRET}}
          tenant-id: ${{env.TENANT_ID}}
          path: out/exportmanaged/${{matrix.solution}}.zip
      - name: Upload the ready to ship solution to GH artifact store
        uses: actions/upload-artifact@v2
        with:
          name: managedSolutions
          path: out/exportmanaged/${{matrix.solution}}.zip

  #Export ManagesSolutions from Dev Environment
  ExportUnManaged-From-DEV:
    runs-on: windows-latest
    needs: [Connection]
    env:
      RUNNER_DEBUG: 1
    strategy:
      matrix: 
        solution: 
          - poc1
          - poc2
     
    steps:
      - name: Export solution ${{matrix.solution}}
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{env.SOURCE_ENV_URL}}
          app-id: ${{env.APPID}}
          client-secret: ${{env.CLIENT_SECRET}}
          tenant-id: ${{env.TENANT_ID}}
          solution-name: ${{matrix.solution}}
          solution-output-file: out/exportunmanaged/${{matrix.solution}}.zip
      - name: Check Solution ${{matrix.solution}}
        uses: microsoft/powerplatform-actions/check-solution@v0
        with:
          environment-url: ${{env.SOURCE_ENV_URL}}
          app-id: ${{env.APPID}}
          client-secret: ${{env.CLIENT_SECRET}}
          tenant-id: ${{env.TENANT_ID}}
          path: out/exportunmanaged/${{matrix.solution}}.zip
      - name: Upload the ready to ship solution to GH artifact store
        uses: actions/upload-artifact@v2
        with:
          name: UnManagedSolutions
          path: out/exportunmanaged/${{matrix.solution}}.zip
  #Import Solutions to QA Envirnoment
  ImportTo-QA:
    needs: [ExportManaged-From-DEV, ExportUnManaged-From-DEV]
    runs-on: windows-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     #checkout git repo
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Fetch the ready to ship solution ${{env.CUSTOMIZATION}} from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: drop/${{ steps.date.outputs.date }}/managed/
    - name: Fetch the ready to ship solution ${{env.CUSTOMIZATION}} from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: UnManagedSolutions
        path: drop/${{ steps.date.outputs.date }}/unmanaged/
    - name: Push the Solutions to Repo
      run: |
            git config --global user.name 'GitHub Workflow'
            git config --global user.email 'githubworkflow@github.com'
            git add .
            git status
            git commit -m "adding solution for build dated ${{ steps.date.outputs.date }}"
            git push origin main
      #Import MCSE2EProductivityR1Customization
    - name: Import ${{env.CUSTOMIZATION}} Solution to ${{env.TARGET_ENV_NAME}} Environment
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.TARGET_ENV_URL}}
        app-id: ${{env.APPID}}
        client-secret: ${{env.CLIENT_SECRET}}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: drop/${{ steps.date.outputs.date }}/managed/${{env.CUSTOMIZATION}}.zip
        force-overwrite: true
        publish-changes: true
        run-asynchronously: true
    # Import MCSE2EProductivityR1Tables
    - name: Import ${{env.TABLES}} Solution to ${{env.TARGET_ENV_NAME}} Environment
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.TARGET_ENV_URL}}
        app-id: ${{env.APPID}}
        client-secret: ${{env.CLIENT_SECRET}}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: drop/${{ steps.date.outputs.date }}/managed/${{env.TABLES}}.zip
        force-overwrite: true
        publish-changes: true
        run-asynchronously: true
    
